name: assignment9
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython=7.12.0
  - matplotlib=3.1.3
  - nbconvert=5.6.1
  - numpy=1.18.1
  - python=3.8.1
  - seaborn=0.10.0
  - opencv=4.2.0
  - pandas=1.0.1
  - scikit-image=0.16.2
